[build]
  publish = "."

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/skills"
  to = "/skills.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/experience"
  to = "/experience.html"
  status = 200

[[redirects]]
  from = "/education"
  to = "/education.html"
  status = 200

[[redirects]]
  from = "/certifications"
  to = "/certifications.html"
  status = 200